version: "3"

services:
  ss-server:
    image: shadowsocks/shadowsocks-libev:v3.3.5
    container_name: ss-server
    hostname: ss-server
    restart: always
    network_mode: "bridge"
    ports:
      - 8388:8388
      - 8388:8388/udp
    environment:
      - PASSWORD=hello,world
      - METHOD=chacha20-ietf-poly1305
      - ARGS=-v
    # volumes:
    #   - /dev/urandom:/dev/random
    command: ss-server \
      -s $SERVER_ADDR \
      -p $SERVER_PORT \
      -k ${PASSWORD:-$(hostname)} \
      -m $METHOD \
      -t $TIMEOUT \
      -d $DNS_ADDRS \
      -u \
      $ARGS
