version: "3.7"

services:
  caddy:
    # If you specify `image` as well as `build`, then Compose names the built image specified in `image`.
    image: custom-caddy:2.4.6
    build:
      context: .
      args:
        VERSION: "2.4.6"
    restart: always
    container_name: caddy
    hostname: caddy
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      # - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./config.json:/etc/caddy/config.json
    # environment:
    #   - EMAIL=your@email.me
    #   - CF_API_TOKEN=XXXXX
    env_file:
      - .env
    network_mode: "bridge"
    command: ["caddy", "run", "--config", "/etc/caddy/config.json"]
