version: "3.9"

services:
  caddy:
    # If you specify `image` as well as `build`, then Compose names the built image specified in `image`.
    image: custom-caddy:2.4.6
    build:
      context: .
      args:
        VERSION: "2.4.6"
    container_name: caddy
    hostname: caddy
    restart: always
    ports:
      # - 80:80
      - 443:443
      - 443:443/udp  # quic
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
      # - ./config.json:/etc/caddy/config.json
    # environment:
    #   DOMAIN: example.com
    #   EMAIL: hello@example.com
    #   # USERNAME:
    #   # PASSWORD:
    #   # PROBE_RESISTANCE_LINK:
    env_file:
      - .env
    network_mode: "bridge"
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
