version: "3"

services:
  web:
    image: gitea/gitea:latest
    container_name: gitea-postgres
    hostname: gitea-postgres
    restart: always
    volumes:
      - data:/data
    environment:
      - RUN_MODE=prod
      - USER_UID=1000
      - USER_GID=1000
      - DISABLE_SSH=true
      - DISABLE_REGISTRATION=true
      - ROOT_URL=
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_USER=
      - DB_PASSWD=
      - DB_NAME=
    ports:
      - 3000:3000
      # - 22:22
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: gitea-postgres
    hostname: gitea-postgres
    restart: always
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  data:
  db:
