version: "3.8"

services:
  emby:
    image: emby/embyserver:4.6.4.0
    container_name: embyserver
    # runtime: nvidia # Expose NVIDIA GPUs
    restart: always
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as
      - GID=100 # The GID to run emby as
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as
    volumes:
      - /mnt/nas0/var/lib/emby/config:/config # Configuration directory
      - /mnt/nas0/collections/Videos:/mnt/share1
      # - /path/to/tvshows:/mnt/share1 # Media directory
      # - /path/to/movies:/mnt/share2 # Media directory
    ports:
      - 8096:8096 # HTTP port
      # - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      # - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
