version: "3"

services:
  pihole:
    image: pihole/pihole:2022.01.1
    container_name: pihole
    hostname: pihole
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 67:67/udp  # Only required if you are using Pi-hole as your DHCP server
      - 5380:80/tcp
      # - 80:80/tcp
      # - 443:443/tcp
    environment:
      TZ: "Asia/Shanghai"
      DNSSEC: "true"
      DNSMASQ_LISTENING: "all"  # set to `all` if network_mode="bridge"
      WEBPASSWORD: "${WEBPASSWORD:-random}"
      FTLCONF_BLOCKINGMODE: "NULL"
    volumes:
      - ./etc-pihole:/etc/pihole/
      - ./etc-dnsmasq.d:/etc/dnsmasq.d/
    # cap_add:
    #   - NET_BIND_SERVICE  # enabled by default
    #   - NET_ADMIN  # required by DHCP
    network_mode: "bridge"
