version: "3"

services:
  sslocal:
    image: sgrio/alpine-sslocalproxy
    container_name: ss-local-privoxy
    hostname: ss-local-privoxy
    restart: always
    ports:
      - 1080:1080
      - 8118:8118
    volumes:
      - /dev/urandom:/dev/random
      - ./config.json:/etc/shadowsocks-libev/config.json
      # - ./privoxy-config:/etc/privoxy/config
      # - ./gfwlist.action:/etc/privoxy/gfwlist.action
    network_mode: "bridge"
