version: "3"

services:
  sslocal:
    image: sgrio/alpine-sslocalproxy
    container_name: ss-local
    hostname: ss-local
    restart: always
    volumes:
      - /dev/urandom:/dev/random
      - ./config.json:/etc/shadowsocks-libev/config.json
    network_mode: "bridge"
    # extra_hosts: ss-local
    # networks:
    #   bridge:
    #     ipv4_address: 172.17.0.6

# networks:
#   bridge:
#     external: true
