version: "3"

services:
  adguard-home:
    image: adguard/adguardhome:v0.107.2
    container_name: adguard-home
    hostname: adguard-home.local
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5380:80/tcp
      - 3000:3000/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    network_mode: "bridge"
