version: "3"

services:
  portainer:
    image: portainer/portainer:1.24.0
    container_name: portainer
    hostname: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      # - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      # - ./data:/data
    network_mode: "bridge"

volumes:
  data:
