version: "3"

services:
  gitlab-ce:
    image: gitlab/gitlab-ce:12.0.3-ce.0
    restart: always
    container_name: gitlab-ce
    hostname: gitlab-ce
    domainname: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.example.com' # influence email notification service
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        # Add any other gitlab.rb configuration here, each on its own line
        ## smtp
        # gitlab_rails['smtp_enable'] = true
        # gitlab_rails['smtp_address'] = "smtp.server"
        # gitlab_rails['smtp_port'] = 465
        # gitlab_rails['smtp_user_name'] = "smtp user"
        # gitlab_rails['smtp_password'] = "smtp password"
        # gitlab_rails['smtp_domain'] = "example.com"
        # gitlab_rails['smtp_authentication'] = "login"
        # gitlab_rails['smtp_enable_starttls_auto'] = true
        # gitlab_rails['smtp_tls'] = false
        # gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        ## email notification
        # gitlab_rails['gitlab_email_display_name'] = 'Example'
        # gitlab_rails['gitlab_email_from'] = 'example@example.com'
        # gitlab_rails['gitlab_email_reply_to'] = 'noreply@example.com'
    ports:
      - 80:80
      - 443:443
      # - 22:22
    volumes:
      # - ./gitlab/config:/etc/gitlab
      # - ./gitlab/logs:/var/log/gitlab
      # - ./gitlab/data:/var/opt/gitlab
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
    network_mode: bridge
    depends_on:
      - plantuml
      - gitlab-runner
    external_links:
      - plantuml:plantuml
      - gitlab-runner:gitlab-runner

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine-v11.9.2
    restart: always
    container_name: gitlab-runner
    hostname: gitlab-runner
    domainname: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
      # - /srv/gitlab-runner/config:/etc/gitlab-runner
    network_mode: bridge
    # depends_on:
    #   - gitlab-ce
    # external_links:
    #   - gitlab-ce:gitlab-ce

  plantuml:
    image: plantuml/plantuml-server:jetty
    restart: always
    container_name: plantuml
    hostname: plantuml
    domainname: plantuml
    network_mode: bridge
    # ports:
    #   - 8080:8080

volumes:
  gitlab-config:
  gitlab-data:
  gitlab-logs:
  gitlab-runner-config:
