version: "3"

services:
  caddy:
    image: custom-caddy
    build:
      context: .
      args:
        VERSION: "2.4.6"
    container_name: caddy
    hostname: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 443:443/udp # quic
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${GITLAB_HOME:-/opt/gitlab}/caddy/data:/data
      - ${GITLAB_HOME:-/opt/gitlab}/caddy/config:/config
      - ${GITLAB_HOME:-/opt/gitlab}/caddy/logs:/logs

  gitlab-ce:
    image: gitlab/gitlab-ce:14.7.1-ce.0
    restart: always
    container_name: gitlab-ce
    hostname: gitlab-ce
    environment:
      GITLAB_ROOT_PASSWORD: "${GITLAB_ROOT_PASSWORD?}"
      GITLAB_OMNIBUS_CONFIG: |
        ### Add any gitlab.rb configuration here, each on its own line
        external_url "https://gitlab.example.com"
        gitlab_rails['time_zone'] = "Asia/Shanghai"
        gitlab_rails['initial_shared_runners_registration_token'] = "gitlab-runners-reg-token"
        # explicitly disable Geo module
        gitlab_rails['geo_registry_replication_enabled'] = false
        geo_secondary['auto_migrate'] = false

        ### Default project feature settings
        gitlab_rails['gitlab_default_projects_features_container_registry'] = false
        gitlab_rails['gitlab_default_projects_features_builds'] = true

        ### smtp
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "example.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "gitlab@example.com"
        gitlab_rails['smtp_password'] = "..."
        gitlab_rails['smtp_domain'] = "example.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = "none"
        # gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_ssl'] = true
        gitlab_rails['smtp_pool'] = true
        # email notification
        gitlab_rails['gitlab_email_display_name'] = "example Gitlab"
        gitlab_rails['gitlab_email_from'] = "gitlab@example.com"
        gitlab_rails['gitlab_email_reply_to'] = "gitlab@example.com"
        # incoming email (for reply by email functional)
        gitlab_rails['incoming_email_enabled'] = true
        gitlab_rails['incoming_email_address'] = "gitlab+%{key}@example.com"
        gitlab_rails['incoming_email_email'] = "gitlab@example.com"
        gitlab_rails['incoming_email_password'] = "..."
        gitlab_rails['incoming_email_host'] = "example.com"
        gitlab_rails['incoming_email_port'] = 993
        # gitlab_rails['incoming_email_ssl'] = true
        gitlab_rails['incoming_email_start_tls'] = true

        ### gitlab pages
        pages_external_url "http://pages.example.com"
        gitlab_pages['enable'] = true
        gitlab_pages['listen_proxy'] = "0.0.0.0:8090"
        gitlab_pages['propagate_correlation_id'] = true
        gitlab_pages['access_control'] = true
        gitlab_pages['enable_disk'] = true
        gitlab_pages['redirect_http'] = false
        # pages_nginx['enable'] = false
        # pages_nginx['listen_port'] = 80
        # pages_nginx['listen_https'] = false
        # pages_nginx['redirect_http_to_https'] = false

        ### gitlab container registry
        registry_external_url "https://container.registry.example.com"
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "container.registry.example.com"
        gitlab_rails['registry_port'] = "443"
        registry['registry_http_addr'] = "0.0.0.0:5000"
        registry_nginx['enable'] = false

        ### gitlab package registry
        gitlab_rails['packages_enabled'] = true
        gitlab_rails['dependency_proxy_enabled'] = true

        ### puma worker
        puma['enable'] = true
        puma['worker_processes'] = 3

        ### disable internal nginx
        nginx['enable'] = false
        gitlab_rails['trusted_proxies'] = ["0.0.0.0"]
        gitlab_workhorse['listen_network'] = "tcp"
        gitlab_workhorse['listen_addr'] = "0.0.0.0:8181"
        # Add whatever user runs under to the following setting unless root
        web_server['external_users'] = ["caddy", "root"]
    ports:
      - 127.0.0.1:8181:8181 # gitlab
      - 127.0.0.1:8090:8090 # pages
      - 127.0.0.1:5000:5000 # container registry
      - 22:22
    volumes:
      - ${GITLAB_HOME:-/opt/gitlab}/config:/etc/gitlab
      - ${GITLAB_HOME:-/opt/gitlab}/logs:/var/log/gitlab
      - ${GITLAB_HOME:-/opt/gitlab}/data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine3.14-v14.7.0
    restart: always
    container_name: gitlab-runner
    hostname: gitlab-runner
    ports:
      - 127.0.0.1:8093:8093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GITLAB_HOME:-/opt/gitlab}/runner-config:/etc/gitlab-runner

  kroki:
    image: yuzutech/kroki:0.16.0
    depends_on:
      - kroki-blockdiag
      - kroki-mermaid
    environment:
      - KROKI_BLOCKDIAG_HOST=kroki-blockdiag
      - KROKI_MERMAID_HOST=kroki-mermaid
    ports:
      - 127.0.0.1:8000:8000

  kroki-blockdiag:
    image: yuzutech/kroki-blockdiag:0.16.0
    expose:
      - "8001"

  kroki-mermaid:
    image: yuzutech/kroki-mermaid:0.16.0
    expose:
      - "8002"
