version: "3"

services:
  zookeeper:
    image: zookeeper:3.6.1
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    # Note: you cannot scale a service beyond 1 container if you have specified a custom name.
    # container_name: kafka
    restart: always
    ports:
      - 9092
    environment:
      PORT_COMMAND: "docker port $$(hostname) 9092/tcp | cut -d: -f2"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP?}:_{PORT_COMMAND}
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    restart: always
    ports:
      - 9001:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
