version: "3.8"

services:
  wireguard:
    image: linuxserver/wireguard:v1.0.20200827-ls34
    container_name: wireguard
    network_mode: "bridge"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - SERVERURL=${SERVERURL?}  #optional
      - SERVERPORT=51820  #optional
      - PEERS=3  #optional
      - PEERDNS=auto  #optional
      - INTERNAL_SUBNET=10.13.13.0  #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/app/wireguard-tools/contrib/reresolve-dns/reresolve-dns.sh /config/wg0.conf || exit 1",
        ]
      interval: 24h
      timeout: 10s
      retries: 3
      start_period: 60s
